### PR TITLE
Draft: Add support for SPI.

### PR DESCRIPTION
**Pull request by mgottschlag**
This PR adds support for SPI. As with the other PRs, the code is mostly taken from the stm32g0xx-hal project, with minor changes to the interaction with RCC.

The code is currently untested and lacks a suitable example.

### CODE REVIEW

**Comment by luctius** [comment]
I had an intern looking at SPI, but he was struggling a bit. Would you mind if he takes this up further?

**Comment by mgottschlag** [comment]
Sure, go ahead.

**Comment by NandoBongers** [comment]
I tested your code with the example in PR #36. It all seems to work!

**Comment by luctius** [comment]
@mgottschlag : are you comfortable with merging this pr?

**Comment by mgottschlag** [comment]
I'd like seeing some more doc comments, but I do not have the time for that at the moment, so go ahead.

**Pull request merged**
