### PR TITLE
[2] Sysconfig

### PR DESCRIPTION
**Pull request by luctius**
Adds basic Sysconfig Support

### CODE REVIEW

**Comment by luctius** [comment]
@dotcypress, Could any of you take a look at the other pull requests too please?

**Comment by dotcypress** [comment]
@luctius wow! There are a lot of PR's, thank you!
I can take a look later today.

I'm not have a lot of free time for stm32g4xx and I'm thinking about adding you as collaborator here, what do you think?

**Comment by luctius** [comment]
> @luctius wow! There are a lot of PR's, thank you!
> I'm not have a lot of free time for stm32g4xx and I'm thinking about adding you as collaborator here, what do you think?

We are a small team working on stm32g4xxx and have more work incoming (SPI and FdCAN being directly in the pipeline). My hope is to generate enough momentum that other people start using this and we can in turn benefit from their improvements, so I would be more than willing to spend the time in this repository.

**Comment by dotcypress** [comment]
Great! 🦀

Invite sent.

**Pull request merged**
