### PR TITLE
Fix `PLLSrc` enum not matching capitalisation conventions

### PR DESCRIPTION
**Pull request by liamkinne**
`PLLSrc` -> `PllSrc`

### CODE REVIEW

**Comment by liamkinne** [comment]
@usbalbin not sure if you have write permissions yet, but here's another PR to look at. Thanks.

**Comment by usbalbin** [comment]
> @usbalbin not sure if you have write permissions yet, but here's another PR to look at. Thanks.

I do not, as far as I know.

LGTM! :)

However I would (unless this does that) prefer to fix the CI errors first

**Comment by liamkinne** [comment]
@usbalbin the CI errors are all to do with typos which I've fixed in #128. Still waiting on getting that merged as well.

**Comment by usbalbin** [comment]
Great!

However there are, as far as I can tell, still [some clippy warnings](https://github.com/stm32-rs/stm32g4xx-hal/actions/runs/10124403903/job/27998709804?pr=128) left for #128.

**Review by usbalbin — APPROVED** [review]
Thanks! :)

**Pull request merged**
